### ISSUE TITLE
Diggro DI01 tilt to wake and AOD not working

### ISSUE THREAD

**Issue by DiggroDI01** [AsteroidOS/meta-mtk6580-hybris#15]
Please 🙏 fix one out of two as soon as possible.reflashed stock room but love to use asteroidos.

**Comment by MagneFire** [comment]
I had a look into this some time ago.
For Always-on-Display we depend on a backend function from Android. This unfortunately does not support the Always-on-Display functionality.

When it comes to Tilt-to-Wake. Looking again at https://github.com/AsteroidOS/meta-mtk6580-hybris/issues/13, I can see different sensors that may be responsible for Tilt-to-Wake. I can build a different image that uses one of those sensors as input for the current Tilt-to-Wake implementation. I should mention that I can't test this, because I don't own a mtk6580 based watch.

Meanwhile, can you send logs of your current stock rom? I'm mainly interested in the (full) `dmesg` and `logcat` output.

**Comment by DiggroDI01** [comment]
Sir I will test it on my DiggroDI01. Sir as I mentioned reflashed stock one but I will flash asteroidos again this weekend then I will send you log file.

**Comment by MagneFire** [comment]
I actually would like the log files from your stock rom :smile: 
Also, can you confirm that the stock roms has Tilt-to-Wake working?

**Comment by DiggroDI01** [comment]
Yes sir on stock tilt to wake working fine. That's why returned to stock.cause no AOD on stock but need battery as well so tilt to wake works.sir should I use app to get log or please suggest me.

**Comment by MagneFire** [comment]
Great!
You can use `adb` for this, you can install it from here: http://download.clockworkmod.com/test/UniversalAdbDriverSetup.msi.
Then you'll need to enable adb debugging on the watch, this is an option in the developer options.
Once enabled you should be able to open a shell connection to the watch using the command: `adb shell` in the (assuming) Windows command prompt.
From there you'll be able to execute the `dmesg` and `logcat` commands.

**Comment by DiggroDI01** [comment]
Sir found this app on play store I have rooted my watch should I send you only kernel log or all log?
![20210305_202241](https://user-images.githubusercontent.com/79909267/110128238-c70be280-7df0-11eb-9e50-a45cd6b90d1d.jpg)
![20210305_202220](https://user-images.githubusercontent.com/79909267/110128251-cb380000-7df0-11eb-8556-d1205c18cd0d.jpg)

**Comment by MagneFire** [comment]
It looks like these contain the `dmesg` log and `logcat` log. So yes, you can send me all of it :smile:

**Comment by MagneFire** [comment]
I went ahead and build two images based on the `test_sensors` output from https://github.com/AsteroidOS/meta-mtk6580-hybris/issues/13.
Basically the tilt to wake sensor used within `sensorfw` now is either one of the following:
```
=== Sensor 7 ==
Name: BOSCH Tilt Detector Sensor
Vendor: Bosch Sensortec GmbH
Version: 0x1
Handle: 0x1c46
Type: 22
maxRange: 1
resolution: 1
power: 0 mA
minDelay: 0

=== Sensor 8 ==
Name: BOSCH Wake Gesture Sensor
Vendor: Bosch Sensortec GmbH
Version: 0x1
Handle: 0x1c47
Type: 23
maxRange: 1
resolution: 1
power: 0 mA
minDelay: -1
```

Can you test them both and report if they fix tilt-to-wake for you? Also, if both work, can you tell me which works better?
Only the `ext4`: https://www.dropbox.com/sh/ehsizm6lwqhemym/AABYNBQYB2am6jsnNCrggNR3a
For the other files you can use the ones from https://asteroidos.org/install/harmony/

**Comment by DiggroDI01** [comment]
[2021-03-05_21.08.zip](https://github.com/AsteroidOS/meta-mtk6580-hybris/files/6094182/2021-03-05_21.08.zip)

**Comment by DiggroDI01** [comment]
Sir downloaded the first one but 2nd getting error downloading.

**Comment by DiggroDI01** [comment]
Sir tilt to wake working on tilt version but wake version didn't worked.one more thing app opening lags on both version, power off and reboot hangs had long press power button to reboot.at first boot everything was upsidedown but after opening one app it's got fixed.

**Comment by MagneFire** [comment]
Excellent! Great to see it working already :smile:

That being said I have some more questions:
 -*asteroid-image-harmony-tilt.ext4*: Is the behavior exactly the same as with the stock rom? Or is it only at a specific angle as suggested by the documentation that Google provides for this sensor.
 -*asteroid-image-harmony-wakegesture.ext4*: Did this version not work because you couldn't install this or does the it actually not wake the screen when doing the tilt-to-wake gesture? (I was hoping that this would be the best solution, that's why I ask this very specific question :smile:)
 -*Lags*: We recently upgraded the base system to the most recent version (https://github.com/AsteroidOS/meta-asteroid/pull/57). Unfortunately, it seems that this introduces the issue where the system can be laggier than before. Can you confirm that after a few minutes the lag goes away?
 -*Power off and reboot*: This was also true with the images provided on the install page (https://asteroidos.org/install/harmony/)?
 -*Upside down issue*: You mentioned this on IRC too right? Not sure what would be the exact reason for this can you try the **in**hamony (https://asteroidos.org/install/inharmony/) version to see if this fixes the issue? (*in* actually refers to inverted screen)

**Comment by DiggroDI01** [comment]
Sir I didn't understand first question about behavior u mean how I tilt the watch ? And sir I did installed both.u made this for us there's no reason to lie 🤭and sir yes lag goes after few minutes. Sir upside down launcher get fix when open any app.sir I will download inharmony image this weekend and let you know about the result. And forgive my poor english.

**Comment by MagneFire** [comment]
I mean if the wrist movement is the same for waking the screen. The specification of this sensor is very specific:
```
A tilt event should be generated if the direction of the 2-seconds window average gravity changed by at least 35 degrees since the activation of the sensor.
```
Full available here: https://android.googlesource.com/platform/hardware/libhardware/+/6f1a00e29a43ca449ae10eb16ff4dfda3c4cd619/include/hardware/sensors.h#586

Also, with regards to the lag, I think I have a solution for this which will implemented in the next build.

Don't worry about your English, we understand each other perfectly :smile:

Thanks for testing btw. It's great to see the support for this watch improving :+1:

**Comment by DiggroDI01** [comment]
Sir wrist movement same as stock and in your both version it's not lag it's actually camera app not working I thought maybe be it's lag but it's not I waited few minutes to see it opens up or not but it doesn't.and can't open wifi I mean I can switch wifi on off but can't go there to input said and pass.

**Comment by DiggroDI01** [comment]
Sir one more thing after few times when watch goes to idle mode and tried to wake the screen with tilt or power button it doesn't wake up but it's running as dark light appears . How to fix this issue if this is fix asteroidos will be fixed totally for me as I don't use camera so much ☺️

**Comment by MagneFire** [comment]
Thanks for letting me know about the wrist movement behavior :smile:

How do you mean the dark light appears? Is this AOD mode? In that case, does this also happen when you disable `Always-on-Display` in the settings app?

With regards to the camera app, can you try to get a log? What you do is connect the watch to your computer and open a shell using the `adb shell` command in the command prompt or powershell. Launch the camera app. Next type in the `adb shell` the command: `journalctl --no-pager` and copy the entire log here :smile:

**Comment by ChandlerSwift** [comment]
It looks like this thread is tracking several separate issues:
- [ ] Tilt to wake not working -- @MagneFire has fixed?
- [ ] AOD not working -- not possible on this device
- [ ] Power off/reboot not working -- looks like a dupe of https://github.com/AsteroidOS/meta-mtk6580-hybris/issues/12
- [ ] App opening lags on both version -- @MagneFire has fixed?
- [x] at first boot everything was upsidedown but after opening one app it's got fixed -- I fixed this one with https://github.com/AsteroidOS/meta-mtk6580-hybris/pull/18\
- [ ] Camera app not working -- I've been taking a look at this one; haven't found anything yet. Just opened an issue to track -- https://github.com/AsteroidOS/asteroid-camera/issues/3
- [ ] No wifi network settings in the UI -- this is a feature AsteroidOS doesn't have yet. https://github.com/AsteroidOS/asteroid/issues/41, https://github.com/AsteroidOS/asteroid-settings/issues/32
- [ ] "after few times when watch goes to idle mode and tried to wake the screen with tilt or power button it doesn't wake up but it's running as dark light appears" -- not sure what this one means.

**Comment by MagneFire** [comment]
It looks like we now have dedicated separate issues for everything mentioned in this issue.
Once we have clarification on what ""after few times when watch goes to idle mode and tried to wake the screen with tilt or power button it doesn't wake up but it's running as dark light appears" means we can close this issue.

Always-on-Display is now also listed in this issue: https://github.com/AsteroidOS/meta-mtk6580-hybris/issues/20
Tilt-to-Wake has now also been fixed as of https://github.com/AsteroidOS/meta-mtk6580-hybris/commit/7ca4e66567d18e8b4fb93ede62097821f7187b57.
